#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 0
bspc config border_width 3
bspc config window_gap 5
bspc config split_ratio 0.5
bspc config focused_border_color "#000000"
bspc config normal_border_color "#ffffff"
