runtime! archlinux.vim

map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>
imap <up> <nop>
imap <down> <nop>
imap <left> <nop>
imap <right> <nop>

set tabstop=4
set expandtab
set nohlsearch
set nowrap
set incsearch
set signcolumn=no
set belloff=all
set shiftwidth=4
set nobackup
set ignorecase
set smartcase
set showcmd
set showmatch
set showmode
set wildmenu
set wildmode=list:longest
